name: 'PR Comments - Dev Herald'
description: 'Post automated PR comments with sticky updates and pre-built templates for deployments, tests, and more. By Dev Herald'
branding:
  icon: 'message-circle'
  color: 'blue'
inputs:
  api-key:
    description: 'Dev Herald API key for authentication (required)'
    required: true
  pr-number:
    description: 'Pull request number to comment on (required, e.g., 123)'
    required: true
  comment:
    description: 'Markdown comment text (for simple comments). Use this OR template, not both. Example: "## Build Complete\n✅ All checks passed!"'
    required: false
  template:
    description: 'Template type for rich comments (use with template-data). Options: DEPLOYMENT, MIGRATION, CUSTOM_TABLE'
    required: false
  template-data:
    description: 'JSON string with template-specific data (required when using template, unless result-location is provided). See README for schema examples.'
    required: false
  test-results:
    description: |
      YAML list of named test result files. When provided with signal: TEST_RESULTS,
      the action reads and parses these files automatically — no template-data needed.
      Each entry requires a display name and a path to a JSON reporter output file.
      Supported formats: Playwright JSON reporter, Vitest JSON reporter.

      Example:
        test-results: |
          - name: Unit Tests
            path: vitest-results/unit.json
          - name: E2E Tests
            path: playwright-results/results.json
    required: false
  signal:
    description: 'Signal type to run. Supported: DEPENDENCY_DIFF, TEST_RESULTS. When set, the action computes the signal output and posts it automatically — no template or template-data required. Cannot be used together with "template".'
    required: false
  include:
    description: 'Comma-separated list of dependency fields to scan for DEPENDENCY_DIFF. Default: dependencies,devDependencies,optionalDependencies'
    required: false
    default: 'dependencies,devDependencies,optionalDependencies'
  enable-cve:
    description: 'Set to "true" to query the OSV database for CVE counts per dependency version (DEPENDENCY_DIFF only). Default: false'
    required: false
    default: 'false'
  max-deps:
    description: 'Maximum number of dependency changes to show in the DEPENDENCY_DIFF table. Default: 25'
    required: false
    default: '25'
  sticky-id:
    description: 'Optional identifier for updateable comments. Comments with the same sticky-id will update instead of creating new ones. Example: "deployment-status"'
    required: false
  api-url:
    description: 'Dev Herald API base URL (optional, defaults to production URL)'
    required: false
    default: 'https://dev-herald.com/api/v1/github'
outputs:
  comment-id:
    description: 'Internal Dev Herald comment ID'
  github-comment-id:
    description: 'GitHub comment ID'
  github-comment-url:
    description: 'Direct URL to the GitHub comment'
  status:
    description: 'Status of the comment (e.g., pending, posted)'
  response:
    description: 'Full JSON response from the API'
runs:
  using: 'node20'
  main: 'dist/index.js'

