name: 'PR Comments - Dev Herald'
description: 'Post automated PR comments with sticky updates and pre-built templates for deployments, tests, and more. By Dev Herald'
branding:
  icon: 'message-circle'
  color: 'blue'
inputs:
  api-key:
    description: 'Dev Herald API key for authentication (required)'
    required: true
  pr-number:
    description: 'Pull request number to comment on (required, e.g., 123)'
    required: true
  comment:
    description: 'Markdown comment text (for simple comments). Use this OR template, not both. Example: "## Build Complete\n✅ All checks passed!"'
    required: false
  template:
    description: 'Template type for rich comments (use with template-data). Options: DEPLOYMENT, TEST_RESULTS, MIGRATION, CUSTOM_TABLE'
    required: false
  template-data:
    description: 'JSON string with template-specific data (required when using template, unless result-location is provided). See README for schema examples.'
    required: false
  test-results:
    description: 'Path(s) to test result file(s). Supports multiple newline-separated paths. When provided with template: TEST_RESULTS, the action reads and parses these files automatically — no template-data needed. Supported formats: Playwright JSON reporter, Vitest JSON reporter.'
    required: false
  sticky-id:
    description: 'Optional identifier for updateable comments. Comments with the same sticky-id will update instead of creating new ones. Example: "deployment-status"'
    required: false
  api-url:
    description: 'Dev Herald API base URL (optional, defaults to production URL)'
    required: false
    default: 'https://dev-herald.com/api/v1/github'
outputs:
  comment-id:
    description: 'Internal Dev Herald comment ID'
  github-comment-id:
    description: 'GitHub comment ID'
  github-comment-url:
    description: 'Direct URL to the GitHub comment'
  status:
    description: 'Status of the comment (e.g., pending, posted)'
  response:
    description: 'Full JSON response from the API'
runs:
  using: 'node20'
  main: 'dist/index.js'

